language: python

env:
    global:
        - PACKAGE="molokai"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

matrix:
    include:
        - os: linux
          python: 3.3

before_install:
    - curl -OL https://raw.githubusercontent.com/gerardroche/UnitTesting/develop/sbin/travis.sh

install:
    - sh travis.sh bootstrap --with-color-scheme-unit

script:
    - sh travis.sh run_color_scheme_tests --coverage

notifications:
    email: false
